// Code generated by sqlc. DO NOT EDIT.
// To regenerate: sqlc generate (from services/supply-chain-api/sqlc/)
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"
)

const getLocation = `-- name: GetLocation :one
SELECT id, name, lat, lng, type
FROM locations
WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id string) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lat,
		&i.Lng,
		&i.Type,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, name, lat, lng, type
FROM locations
ORDER BY name
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByIDs = `-- name: ListLocationsByIDs :many
SELECT id, name, lat, lng, type
FROM locations
WHERE id = ANY($1::text[])
ORDER BY name
`

func (q *Queries) ListLocationsByIDs(ctx context.Context, ids []string) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByType = `-- name: ListLocationsByType :many
SELECT id, name, lat, lng, type
FROM locations
WHERE type = $1
ORDER BY name
`

func (q *Queries) ListLocationsByType(ctx context.Context, type_ LocationType) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
