// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
)

type LocationType string

const (
	LocationTypeSupplier   LocationType = "supplier"
	LocationTypeDc         LocationType = "dc"
	LocationTypeRestaurant LocationType = "restaurant"
)

func (e *LocationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationType(s)
	case string:
		*e = LocationType(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationType: %T", src)
	}
	return nil
}

type NullLocationType struct {
	LocationType LocationType `json:"locationType"`
	Valid        bool         `json:"valid"` // Valid is true if LocationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationType) Scan(value interface{}) error {
	if value == nil {
		ns.LocationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationType), nil
}

type RouteType string

const (
	RouteTypeSupplierToDc   RouteType = "supplier_to_dc"
	RouteTypeDcToRestaurant RouteType = "dc_to_restaurant"
)

func (e *RouteType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RouteType(s)
	case string:
		*e = RouteType(s)
	default:
		return fmt.Errorf("unsupported scan type for RouteType: %T", src)
	}
	return nil
}

type NullRouteType struct {
	RouteType RouteType `json:"routeType"`
	Valid     bool      `json:"valid"` // Valid is true if RouteType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRouteType) Scan(value interface{}) error {
	if value == nil {
		ns.RouteType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RouteType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRouteType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RouteType), nil
}

type Location struct {
	ID   string       `json:"id"`
	Name string       `json:"name"`
	Lat  float64      `json:"lat"`
	Lng  float64      `json:"lng"`
	Type LocationType `json:"type"`
}

type SupplyRoute struct {
	ID        string    `json:"id"`
	SourceID  string    `json:"sourceId"`
	DestID    string    `json:"destId"`
	RouteType RouteType `json:"routeType"`
	Volume    int32     `json:"volume"`
	IsActive  bool      `json:"isActive"`
}
