// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package db

import (
	"context"
)

const listActiveRoutes = `-- name: ListActiveRoutes :many
SELECT id, source_id, dest_id, route_type, volume, is_active
FROM supply_routes
WHERE is_active = true
ORDER BY id
`

func (q *Queries) ListActiveRoutes(ctx context.Context) ([]SupplyRoute, error) {
	rows, err := q.db.Query(ctx, listActiveRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRoute{}
	for rows.Next() {
		var i SupplyRoute
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestID,
			&i.RouteType,
			&i.Volume,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, source_id, dest_id, route_type, volume, is_active
FROM supply_routes
ORDER BY id
`

func (q *Queries) ListRoutes(ctx context.Context) ([]SupplyRoute, error) {
	rows, err := q.db.Query(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRoute{}
	for rows.Next() {
		var i SupplyRoute
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestID,
			&i.RouteType,
			&i.Volume,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByDestId = `-- name: ListRoutesByDestId :many
SELECT id, source_id, dest_id, route_type, volume, is_active
FROM supply_routes
WHERE dest_id = $1
ORDER BY id
`

func (q *Queries) ListRoutesByDestId(ctx context.Context, destID string) ([]SupplyRoute, error) {
	rows, err := q.db.Query(ctx, listRoutesByDestId, destID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRoute{}
	for rows.Next() {
		var i SupplyRoute
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestID,
			&i.RouteType,
			&i.Volume,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesBySourceId = `-- name: ListRoutesBySourceId :many
SELECT id, source_id, dest_id, route_type, volume, is_active
FROM supply_routes
WHERE source_id = $1
ORDER BY id
`

func (q *Queries) ListRoutesBySourceId(ctx context.Context, sourceID string) ([]SupplyRoute, error) {
	rows, err := q.db.Query(ctx, listRoutesBySourceId, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRoute{}
	for rows.Next() {
		var i SupplyRoute
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestID,
			&i.RouteType,
			&i.Volume,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByType = `-- name: ListRoutesByType :many
SELECT id, source_id, dest_id, route_type, volume, is_active
FROM supply_routes
WHERE route_type = $1
ORDER BY id
`

func (q *Queries) ListRoutesByType(ctx context.Context, routeType RouteType) ([]SupplyRoute, error) {
	rows, err := q.db.Query(ctx, listRoutesByType, routeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplyRoute{}
	for rows.Next() {
		var i SupplyRoute
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestID,
			&i.RouteType,
			&i.Volume,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
